### ISSUE TITLE
Don't Automatically Navigate Between Events

### ISSUE THREAD

**Issue by zoidberg187** [flammcon/smash#23]
Current Behavior:Upon entering the final result for an event, a popup declares the rankings and the next event loads. The user doesn't have an opportunity to screenshot the page for the finished event.

Desired Behavior: The page is not automatically navigated away from after the last result is entered. A button should become enabled allowing the user to move forward.

Bonus points if the user can navigate between event pages after the whole tournament is completed, in case they forgot to screenshot in the heat of battle.

This may be irrelevant depending on database/archival effort.

**Comment by marlenecota** [comment]
Fixed by https://github.com/flammcon/smash/commit/cc6f413b0099471c8b2987d93cdc27edfcb62311

Remaining work for bracket state restore will be tracked by #24
