### ISSUE TITLE
2v2 bracket seed numbers

### ISSUE THREAD

**Issue by zoidberg187** [flammcon/smash#4]
The numbers in the 2v2 bracket do not reflect seeds as determined by bloodbath.
<img width="832" alt="2v2" src="https://user-images.githubusercontent.com/4780068/76260866-fd327880-6215-11ea-8f9c-d53ad50746eb.PNG">

**Comment by marlenecota** [comment]
Fixed by https://github.com/flammcon/smash/commit/a5d627a00450213bca739b03bbdb4d1a3ed40bae
