### ISSUE TITLE
Drag/drop UIs should make it clear that things can be re-arranged via up/down arrows

### ISSUE THREAD

**Issue by jsmrcina** [flammcon/smash#8]

**Comment by jsmrcina** [comment]
It's not currently clear which things you can interact with and which ones you can't

**Comment by jsmrcina** [comment]
Partially addressed by #17

**Comment by marlenecota** [comment]
Added grip lines to all draggable lists: https://github.com/flammcon/smash/commit/c5dbc9d609b5e1c463db3f2274e9e180adfe1887
